[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zenmap"
license = {text = "Nmap License (https://nmap.org/book/man-legal.html)"}
dynamic = ["version"]
authors = [{name = "The Nmap Project"}]
description = "Nmap frontend and results viewer"
readme = {file = "README", content-type = "text/plain"}
dependencies = [
  "PyGObject",
]

[project.urls]
Homepage = "https://nmap.org/zenmap/"
Documentation = "https://nmap.org/book/zenmap.html"
Repository = "https://github.com/nmap/nmap.git"
Issues = "https://github.com/nmap/nmap/issues"
Changelog = "https://nmap.org/changelog"

[project.gui-scripts]
zenmap = "zenmapGUI.App:run"

[tool.setuptools]
packages = [
"zenmapCore",
"zenmapGUI",
"zenmapGUI.higwidgets",
"radialnet",
"radialnet.bestwidgets",
"radialnet.core",
"radialnet.gui",
"radialnet.util",
"share",
]

[tool.setuptools.dynamic]
version = {attr = "zenmapCore.Version.VERSION"}

[tool.setuptools.package-data]
"share.zenmap.pixmaps" = ["*.gif", "*.png"]
"share.zenmap.pixmaps.radialnet" = ["*.png"]
"share.zenmap.locale" = ["*.mo"]
"share.zenmap.config" = ["zenmap.conf", "scan_profile.usp", "zenmap_version"]
"share.zenmap.docs" = ["*.html"]
"share.zenmap.misc" = ["*.xml"]
